version: "3.9"

services:

  db:
    image: postgres:17-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
  app:
    build: .
    container_name: rota-management-app
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_MAIL_USERNAME: ${MAIL_USER}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      VERIFICATION_LINK: ${VERIFICATION_LINK}
    depends_on:
      - db
    ports:
      - "8080:8080"