name: CI

on:
  push:
    branches:
      - master

jobs:
  test-and-build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build & Run Unit Tests
        run: mvn clean verify -e -X

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Docker Build & Run
        run: |
          docker compose up --build -d
        env:
          SPRING_PROFILES_ACTIVE: dev
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          VERIFICATION_LINK: ${{ vars.VERIFICATION_LINK }}

      - name: Verify Running Containers
        run: docker ps
