name: CI (develop)

on:
  push:
    branches:
      - develop
      - Shvoruk-workflows

jobs:
  test-and-build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build & Run Unit Tests
        run: mvn clean verify

      - name: Docker Build & Run
        run: |
          docker compose up --build -d

      - name: Verify Running Containers
        run: docker ps
